version: '3.8'

services:
  timescaledb:
    image: timescale/timescaledb:latest-pg15
    container_name: timescaledb
    restart: always
    environment:
      POSTGRES_DB: stockfeed
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - timescaledb_data:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d
    command: ["postgres", "-c", "shared_preload_libraries=timescaledb"]

  redis:
    image: redis:7-alpine
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  app:
    build: .
    container_name: stockfeed_app
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - ./feed_data.txt:/app/feed_data.txt
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@timescaledb:5432/stockfeed
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - timescaledb
      - redis
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

volumes:
  timescaledb_data:
  redis_data: